# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Movilidapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  # Pods for Movilidapp

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket',
    'RCTAnimation',
    'RCTImage',
  ]

  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  
  target 'YourAppNameHereTests' do
    inherit! :search_paths
  end
end


  target 'Movilidapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovilidappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Movilidapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Movilidapp-tvOS

  target 'Movilidapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
